# Generated by Django 5.2.3 on 2025-06-28 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(error_messages='El texto debe tener max 8 digitos', max_length=8, primary_key=True, serialize=False)),
                ('ape_nom', models.CharField(max_length=80)),
                ('fec_reg', models.DateField()),
                ('fec_sis', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=50)),
                ('descrip_prod', models.TextField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fec_vencim', models.DateField()),
                ('fec_reg', models.DateTimeField()),
            ],
        ),
    ]
