# Generated by Django 5.2.3 on 2025-07-05 05:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(error_messages='El texto debe tener max 8 digitos', max_length=8, primary_key=True, serialize=False)),
                ('ape_nom', models.CharField(max_length=80)),
                ('fec_reg', models.DateField()),
                ('fec_sis', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=50)),
                ('descrip_prod', models.TextField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fec_vencim', models.DateField()),
                ('fec_reg', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(error_messages={'max_length': 'Máximo 8 caracteres'}, max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1)])),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('fec_reg', models.DateField()),
                ('fec_sis', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('cod_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.cliente')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.producto')),
            ],
        ),
    ]
