# Generated by Django 5.2.3 on 2025-07-02 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(error_messages={'max_length': 'Máximo 8 caracteres'}, max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1)])),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('fec_reg', models.DateField()),
                ('fec_sis', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
