# Generated by Django 5.2.3 on 2025-07-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.proveedor')),
            ],
        ),
    ]
